version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install deps
          command: sudo make dev-install
      - run:
          name: Linting
          command: make format-check
      - run:
          name: Run tests
          command: make test

  deploy:
    machine:
      image: ubuntu-1604:201903-01 # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images with Docker 18.09.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d3:5f:9d:68:ea:12:9a:42:d3:d3:e1:db:b0:6a:fc:d2"
      - run:
          name: Generate new data, push to PokeAPI/api-data's staging branch, if master open a Pull Request towards PokeAPI/api-data's master branch
          command: bash -x Resources/scripts/updater.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
                - staging
